version: '3.9'

services:
  web:
    build: .
    container_name: student_portal
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3
    command: gunicorn student_portal.wsgi:application --bind 0.0.0.0:8000

volumes:
  sqlite_data:
